version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    restart: always
    depends_on:
      - backend
    networks:
      - crs-network

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    restart: always
    networks:
      - crs-network

networks:
  crs-network:
    driver: bridge
